# Generated by Django 3.1.7 on 2021-02-23 07:20

import db.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.FileField(blank=True, help_text='Choose SQL File', upload_to=db.models.content_file_name,
                                        validators=[django.core.validators.FileExtensionValidator(
                                            allowed_extensions=['sql'])])),
            ],
        ),
    ]
